<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apibeat.proto

namespace GPBMetadata;

class Apibeat
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a80020a0d617069626561742e70726f746f120a617069626561746c6f67" .
            "225e0a0e4c6f675265717565737444617461120f0a077365727669636518" .
            "0120012809120e0a06736f75726365180220012809120c0a04686f737418" .
            "0320012809120f0a076d657373616765180420012809120c0a0464617461" .
            "180520012809222c0a0f4c6f67526573706f6e736544617461120c0a0463" .
            "6f6465180120012809120b0a036d7367180220012809324d0a0741706942" .
            "65617412420a074c6f67496e666f121a2e617069626561746c6f672e4c6f" .
            "6752657175657374446174611a1b2e617069626561746c6f672e4c6f6752" .
            "6573706f6e736544617461620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

